In [32]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [33]:
import pandas as pd 
import numpy as np

In [34]:
df = pd.read_csv('../Datasets/Churn_Modelling.csv')

In [35]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [36]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [37]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [39]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [40]:
df.tail(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [41]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [42]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [43]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,42,41,42,39,43,44,50,29,44,27,...,33,53,36,28,29,39,35,36,42,28
Tenure,2,1,8,1,2,8,7,4,4,2,...,3,4,2,7,2,5,10,7,3,4
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [44]:
df.sort_values('Age')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,4557,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,9527,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,9573,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3531,3532,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0

In [45]:
df["Surname"]

0        Hargrave
1            Hill
2            Onio
3            Boni
4        Mitchell
          ...
9995     Obijiaku
9996    Johnstone
9997          Liu
9998    Sabbatini
9999       Walker
Name: Surname, Length: 10000, dtype: str

In [46]:
df['New Balance'] = df['Balance']+ 1000

In [47]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [48]:
print(df.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1

   EstimatedSalary  Exited  New Balance
0        101348.88       1      1000.00
1        112542.58       0     84807.86
2        113931.57       1    160660.80
3         93826.63       0      1000.00
4         79084.10       0    126510.82

In [49]:
print("Shape : " , df.shape)

Shape :  (10000, 15)

In [50]:
print('Columns : ' , df.columns.to_list())

Columns :  ['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'New Balance']

In [51]:
print(df.describe(include="all"))

          RowNumber    CustomerId Surname   CreditScore Geography Gender  \
count   10000.00000  1.000000e+04   10000  10000.000000     10000  10000
unique          NaN           NaN    2932           NaN         3      2
top             NaN           NaN   Smith           NaN    France   Male
freq            NaN           NaN      32           NaN      5014   5457
mean     5000.50000  1.569094e+07     NaN    650.528800       NaN    NaN
std      2886.89568  7.193619e+04     NaN     96.653299       NaN    NaN
min         1.00000  1.556570e+07     NaN    350.000000       NaN    NaN
25%      2500.75000  1.562853e+07     NaN    584.000000       NaN    NaN
50%      5000.50000  1.569074e+07     NaN    652.000000       NaN    NaN
75%      7500.25000  1.575323e+07     NaN    718.000000       NaN    NaN
max     10000.00000  1.581569e+07     NaN    850.000000       NaN    NaN

                 Age        Tenure        Balance  NumOfProducts    HasCrCard  \
count   10000.000000  10000.000000   10000.000000   10000.000000  10000.00000
unique           NaN           NaN            NaN            NaN          NaN
top              NaN           NaN            NaN            NaN          NaN
freq             NaN           NaN            NaN            NaN          NaN
mean       38.921800      5.012800   76485.889288       1.530200      0.70550
std        10.487806      2.892174   62397.405202       0.581654      0.45584
min        18.000000      0.000000       0.000000       1.000000      0.00000
25%        32.000000      3.000000       0.000000       1.000000      0.00000
50%        37.000000      5.000000   97198.540000       1.000000      1.00000
75%        44.000000      7.000000  127644.240000       2.000000      1.00000
max        92.000000     10.000000  250898.090000       4.000000      1.00000

        IsActiveMember  EstimatedSalary        Exited    New Balance
count     10000.000000     10000.000000  10000.000000   10000.000000
unique             NaN              NaN           NaN            NaN
top                NaN              NaN           NaN            NaN
freq               NaN              NaN           NaN            NaN
mean          0.515100    100090.239881      0.203700   77485.889288
std           0.499797     57510.492818      0.402769   62397.405202
min           0.000000        11.580000      0.000000    1000.000000
25%           0.000000     51002.110000      0.000000    1000.000000
50%           1.000000    100193.915000      0.000000   98198.540000
75%           1.000000    149388.247500      0.000000  128644.240000
max           1.000000    199992.480000      1.000000  251898.090000

In [52]:
# Data cleaning operations

print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
New Balance        0
dtype: int64

In [53]:
# % of missing values
missing_pct = df.isnull().mean().mul(100).sort_values(ascending=False)

In [54]:
missing_pct

RowNumber          0.0
CustomerId         0.0
Surname            0.0
CreditScore        0.0
Geography          0.0
Gender             0.0
Age                0.0
Tenure             0.0
Balance            0.0
NumOfProducts      0.0
HasCrCard          0.0
IsActiveMember     0.0
EstimatedSalary    0.0
Exited             0.0
New Balance        0.0
dtype: float64

In [55]:
# duplicate rows 

print(df.dtypes)

RowNumber            int64
CustomerId           int64
Surname                str
CreditScore          int64
Geography              str
Gender                 str
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
New Balance        float64
dtype: object

In [56]:
df[df.Age <= 20]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
57,58,15647091,Endrizzi,725,Germany,Male,19,0,75888.20,1,0,0,45613.75,0,76888.20
233,234,15723886,Fiore,767,Germany,Male,20,3,119714.25,2,0,1,150135.38,0,120714.25
746,747,15787619,Hsieh,844,France,Male,18,2,160980.03,1,0,0,145936.28,0,161980.03
923,924,15601026,Gallagher,572,Germany,Female,19,1,138657.08,1,1,1,16161.82,0,139657.08
1064,1065,15699598,Smith,723,France,Female,20,4,0.00,2,1,1,140385.33,0,1000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9586,9587,15786418,Chiu,546,France,Female,20,6,0.00,1,0,1,20508.85,0,1000.00
9679,9680,15605067,Nwachinemelu,472,France,Male,19,9,0.00,2,1,0,3453.40,0,1000.00
9782,9783,15728829,Weigel,509,France,Male,18,7,102983.91,1,1,0,171770.58,0,103983.91
9932,9933,15813451,Fleetwood-Smith,677,Spain,Male,18,8,134796.87,2,1,1,114858.90,0,135796.87
9940,9941,15791972,Bergamaschi,748,France,Female,20,7,0.00,2,0,0,10792.42,0,1000.00

In [57]:
df_age = df[df.Age <= 20]

In [58]:
len(df_age)

89

In [59]:
len(df)

10000

In [60]:
df['Age'].fillna(10)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [61]:
# Remove Columns 

df.pop('RowNumber')

0           1
1           2
2           3
3           4
4           5
        ...
9995     9996
9996     9997
9997     9998
9998     9999
9999    10000
Name: RowNumber, Length: 10000, dtype: int64

In [62]:
df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [63]:
df.pop('CustomerId')

0       15634602
1       15647311
2       15619304
3       15701354
4       15737888
          ...
9995    15606229
9996    15569892
9997    15584532
9998    15682355
9999    15628319
Name: CustomerId, Length: 10000, dtype: int64

In [64]:
df

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [65]:
new_df = pd.read_csv('../Datasets/Churn_Modelling.csv')

In [66]:
new_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [68]:
# Apply method 
print(df['Balance'].apply(np.max))

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [69]:
df['Balance'].apply(np.sqrt)

0         0.000000
1       289.495872
2       399.575775
3         0.000000
4       354.275063
           ...
9995      0.000000
9996    239.519540
9997      0.000000
9998    273.998741
9999    360.753087
Name: Balance, Length: 10000, dtype: float64

In [70]:
new_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [75]:
new_df['SqRoot_Balance'] = df['Balance'].apply(np.sqrt)

In [76]:
new_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,SqRoot_Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.000000
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,289.495872
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,399.575775
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.000000
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,354.275063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,0.000000
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,239.519540
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,0.000000
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,273.998741
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,360.753087

In [74]:
df

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [77]:
df.dropna()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [81]:
# Combining so data frame 
# join operations  
# first step to create two different dataframes 
# with one same column name that is my access point and act as primary key like sql


# Employee Database consist only employee id and name 
df1 = pd.DataFrame(
    {
        "emp_id" : [1001,1002,1003,1004,1005],
        "emp_name" : ["Rahul", "Sarthak", "Pranay", "Aman", "Vedant"],
    }
)

# Department Database consist only employee id with salary 

df2 = pd.DataFrame(
    {
        "emp_id" : [1001,1006,1007,1008,1005],
        "emp_salary" : [500000,450000,350000,200000,100000],
    }
)

print("df1 \n",df1)

df1
    emp_id emp_name
0    1001    Rahul
1    1002  Sarthak
2    1003   Pranay
3    1004     Aman
4    1005   Vedant

In [82]:
print("df1 \n",df2)

df1
    emp_id  emp_salary
0    1001      500000
1    1006      450000
2    1007      350000
3    1008      200000
4    1005      100000

In [85]:
# inner join

inner_join = pd.merge(df1, df2, on="emp_id", how='inner')

In [86]:
inner_join

   emp_id emp_name  emp_salary
0    1001    Rahul      500000
1    1005   Vedant      100000

In [87]:
left_join = pd.merge(df1,df2, on="emp_id", how='left')

In [88]:
left_join

   emp_id emp_name  emp_salary
0    1001    Rahul    500000.0
1    1002  Sarthak         NaN
2    1003   Pranay         NaN
3    1004     Aman         NaN
4    1005   Vedant    100000.0

In [90]:
right_join = pd.merge(df1,df2, on="emp_id", how='right')

In [92]:
right_join

   emp_id emp_name  emp_salary
0    1001    Rahul      500000
1    1006      NaN      450000
2    1007      NaN      350000
3    1008      NaN      200000
4    1005   Vedant      100000

In [93]:
# outer join

outer_join = pd.merge(df1,df2,on='emp_id',how='outer')

In [94]:
outer_join

   emp_id emp_name  emp_salary
0    1001    Rahul    500000.0
1    1002  Sarthak         NaN
2    1003   Pranay         NaN
3    1004     Aman         NaN
4    1005   Vedant    100000.0
5    1006      NaN    450000.0
6    1007      NaN    350000.0
7    1008      NaN    200000.0

In [95]:
df1.fillna("Unknown")

   emp_id emp_name
0    1001    Rahul
1    1002  Sarthak
2    1003   Pranay
3    1004     Aman
4    1005   Vedant

In [99]:
print(outer_join["emp_salary"].fillna("not define"))

0      500000.0
1    not define
2    not define
3    not define
4      100000.0
5      450000.0
6      350000.0
7      200000.0
Name: emp_salary, dtype: object

In [100]:
outer_join

   emp_id emp_name  emp_salary
0    1001    Rahul    500000.0
1    1002  Sarthak         NaN
2    1003   Pranay         NaN
3    1004     Aman         NaN
4    1005   Vedant    100000.0
5    1006      NaN    450000.0
6    1007      NaN    350000.0
7    1008      NaN    200000.0

In [110]:
df.loc[0]

Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
New Balance           1000.0
Name: 0, dtype: object

In [105]:
df

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [106]:
# loc and iloc 

s = pd.Series(list('abcdef'), index=[49,48,47,0,1,2])

In [107]:
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: str

In [112]:
s.loc[49]

'a'

In [114]:
s.iloc[-1]

'f'

In [125]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Rahul', 'Priya', 'Amit', 'Sneha'],
    'Age': [25, 30, 22, 28],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Bangalore']
}, index=['a', 'b', 'c', 'd'])   # index labels a, b, c, d

df

    Name  Age       City
a  Rahul   25       Pune
b  Priya   30     Mumbai
c   Amit   22      Delhi
d  Sneha   28  Bangalore

**1. loc (Label based)**
Label (naam) se select karta hai.
Row ya column ka actual naam use karo.
Inclusive hota hai (start aur end dono include).

In [116]:
df

    Name  Age       City
a  Rahul   25       Pune
b  Priya   30     Mumbai
c   Amit   22      Delhi
d  Sneha   28  Bangalore

In [118]:
# Single row by label
df.loc['b']                 # Priya wali row

     # Age 25 se zyada wale

Name     Priya
Age         30
City    Mumbai
Name: b, dtype: object

In [119]:
# Multiple rows
df.loc[['a', 'c']]          # Rahul aur Amit

# Rows + specific columns

    Name  Age   City
a  Rahul   25   Pune
c   Amit   22  Delhi

In [124]:
df.loc['a':'c', ['Name', 'Age']]   # a se c tak, sirf Name aur Age

    Name  Age
a  Rahul   25
b  Priya   30
c   Amit   22

In [126]:

# Condition ke saath
df.loc[df['Age'] >= 25, ['Name']]

    Name
a  Rahul
b  Priya
d  Sneha

**2. iloc (Integer position based)**
Position (number) se select karta hai.
0, 1, 2... jaisa indexing (jaise list me).
Exclusive hota hai end ke liye (Python slicing jaisa).

In [128]:
# First row (position 0)
df.iloc[:1]

    Name  Age  City
a  Rahul   25  Pune

In [129]:

# 2nd aur 4th row (positions 1 aur 3)
df.iloc[[1, 3]]

    Name  Age       City
b  Priya   30     Mumbai
d  Sneha   28  Bangalore

In [ ]:
# Rows 0 se 2 tak (0,1,2) + columns 0 aur 1
df.iloc[0:3, 0:2] # [Rows, Columns]

    Name  Age
a  Rahul   25
b  Priya   30
c   Amit   22

In [135]:
# Last row
df.iloc[-1]

Name        Sneha
Age            28
City    Bangalore
Name: d, dtype: object

In [136]:
json_data = pd.read_json('../Datasets/Sample_data.json')

In [137]:
json_data

   id    name  age       city  salary
0   1   Rahul   25       Pune   45000
1   2   Priya   30     Mumbai   62000
2   3    Amit   22      Delhi   38000
3   4   Sneha   28  Bangalore   55000
4   5  Vikram   35  Hyderabad   72000

In [141]:
display(new_df.sample(min(5, len(df)), random_state=42))

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,SqRoot_Balance
6252,6253,15687492,Anderson,596,Germany,Male,32,3,96709.07,2,0,0,41788.37,0,310.980819
4684,4685,15736963,Herring,623,France,Male,43,1,0.00,2,1,1,146379.30,0,0.000000
1731,1732,15721730,Amechi,601,Spain,Female,44,4,0.00,2,1,0,58561.31,0,0.000000
4742,4743,15762134,Liang,506,Germany,Male,59,8,119152.10,2,1,1,170679.74,0,345.184154