In [1]:
pip install matplotlib seaborn jupyterlab

Requirement already satisfied: matplotlib in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.11.2)
Requirement already satisfied: seaborn in /usr/local/python/3.14.2/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: jupyterlab in /home/codespace/.local/lib/python3.14/site-packages (4.6.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from seaborn) (3.0.6)
Requirement already satisfied: async-lru>=1.0.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (7.3.0)
Requirement already satisfied: jinja2>=3.0.3 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (1.2.3)
Requirement already satisfied: jupyter-core in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (2.21.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (6.5.8)
Requirement already satisfied: traitlets in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab) (5.16.1)
Requirement already satisfied: anyio in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.25.0->jupyterlab) (4.15.1)
Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.25.0->jupyterlab) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.25.0->jupyterlab) (3.19)
Requirement already satisfied: h11>=0.16 in /home/codespace/.local/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (25.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (8.10.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (7.17.1)
Requirement already satisfied: nbformat>=5.3.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (5.11.1)
Requirement already satisfied: prometheus-client>=0.9 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (0.26.0)
Requirement already satisfied: pyzmq>=24 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (27.2.0)
Requirement already satisfied: send2trash>=1.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab) (1.9.2)
Requirement already satisfied: babel>=2.10 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (4.26.0)
Requirement already satisfied: requests>=2.31 in /home/codespace/.local/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (2.34.2)
Requirement already satisfied: typing_extensions>=4.16.0 in /home/codespace/.local/lib/python3.14/site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab) (4.16.0)
Requirement already satisfied: argon2-cffi-bindings in /home/codespace/.local/lib/python3.14/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab) (26.1.0)
Requirement already satisfied: comm>=0.1.1 in /home/codespace/.local/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /home/codespace/.local/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in /home/codespace/.local/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (9.17.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /home/codespace/.local/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in /home/codespace/.local/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.7.2)
Requirement already satisfied: psutil>=5.7 in /home/codespace/.local/lib/python3.14/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (7.2.2)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/codespace/.local/lib/python3.14/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /home/codespace/.local/lib/python3.14/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.20.0)
Requirement already satisfied: pexpect>4.6 in /home/codespace/.local/lib/python3.14/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/codespace/.local/lib/python3.14/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in /home/codespace/.local/lib/python3.14/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /home/codespace/.local/lib/python3.14/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in /home/codespace/.local/lib/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.8.3)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /home/codespace/.local/lib/python3.14/site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.14/site-packages (from jinja2>=3.0.3->jupyterlab) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-core->jupyterlab) (4.11.8)
Requirement already satisfied: python-json-logger>=2.0.4 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (4.2.0)
Requirement already satisfied: pyyaml>=5.3 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (6.0.3)
Requirement already satisfied: rfc3339-validator in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /home/codespace/.local/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (0.1.1)
Requirement already satisfied: fqdn in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (1.5.1)
Requirement already satisfied: isoduration in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (1.1.0)
Requirement already satisfied: uri-template in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /home/codespace/.local/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (25.10.0)
Requirement already satisfied: beautifulsoup4 in /home/codespace/.local/lib/python3.14/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in /home/codespace/.local/lib/python3.14/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (6.4.0)
Requirement already satisfied: defusedxml in /home/codespace/.local/lib/python3.14/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /home/codespace/.local/lib/python3.14/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /home/codespace/.local/lib/python3.14/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in /home/codespace/.local/lib/python3.14/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/codespace/.local/lib/python3.14/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (1.5.1)
Requirement already satisfied: webencodings in /home/codespace/.local/lib/python3.14/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (0.6.1)
Requirement already satisfied: tinycss2>=1.1.0 in /home/codespace/.local/lib/python3.14/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /home/codespace/.local/lib/python3.14/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab) (2.22.2)
Requirement already satisfied: ptyprocess>=0.5 in /home/codespace/.local/lib/python3.14/site-packages (from pexpect>4.6->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.14/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /home/codespace/.local/lib/python3.14/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab) (2.7.0)
Requirement already satisfied: lark>=1.2.2 in /home/codespace/.local/lib/python3.14/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (1.3.1)
Requirement already satisfied: executing>=1.2.0 in /home/codespace/.local/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/codespace/.local/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (3.0.2)
Requirement already satisfied: pure-eval in /home/codespace/.local/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: cffi>=2 in /home/codespace/.local/lib/python3.14/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab) (2.1.1)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.14/site-packages (from cffi>=2->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in /home/codespace/.local/lib/python3.14/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab) (2.9.2)
Requirement already satisfied: arrow>=0.15.0 in /home/codespace/.local/lib/python3.14/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (1.4.0)
Requirement already satisfied: tzdata in /home/codespace/.local/lib/python3.14/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab) (2026.3)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd 
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [3]:
print("Pandas version :", pd.__version__)
print("Numpy version :", np.__version__)
print("Matplotlib version :", matplotlib.__version__)

Pandas version : 3.0.6
Numpy version : 2.5.4
Matplotlib version : 3.11.2

 * Pandas is a Python library for manipulating and analyzing structured data. It provides tools for working with rows and columns, missing values, categorical variables, dates, aggregations, and datasets from CSV, Excel, databases, and other sources.

In [4]:
prices = pd.Series([50000,500,1500])

In [5]:
print(prices)

0    50000
1      500
2     1500
dtype: int64

In [6]:
data = {
    "Product": [
        "Laptop", "Mouse", "Keyboard", "RAM", "SSD 512GB", "HDD 1TB", "Monitor 24inch", "Monitor 27inch",
        "USB Cable", "HDMI Cable", "Webcam", "Headphones", "Speaker", "Microphone", "Graphics Card", "Motherboard",
        "Processor i5", "Processor i7", "Cooling Fan", "Power Supply", "Cabinet", "Laptop Bag", "Mouse Pad", "External HDD",
        "Pendrive 32GB", "Pendrive 64GB", "Pendrive 128GB", "Router", "Switch", "LAN Cable", "Printer", "Scanner",
        "UPS", "Stabilizer", "Extension Board", "Laptop Stand", "Tablet", "Smartphone", "Smartwatch", "Earbuds",
        "Bluetooth Speaker", "Gaming Mouse", "Mechanical Keyboard", "RGB Keyboard", "Wireless Mouse", "Wireless Keyboard", "SSD 1TB", "SSD 2TB",
        "RAM 8GB", "RAM 16GB", "RAM 32GB", "Graphics Card RTX", "Graphics Card GTX", "Webcam HD", "Webcam 4K", "Monitor 32inch",
        "Curved Monitor", "Projector", "VR Headset", "Gaming Chair", "Desk Mat", "Laptop Cooler", "USB Hub", "Card Reader",
        "SD Card 64GB", "SD Card 128GB", "MicroSD 256GB", "External SSD", "Docking Station", "Laptop Charger", "Phone Charger", "Type-C Cable",
        "Lightning Cable", "Wireless Charger", "Power Bank 10000mAh", "Power Bank 20000mAh", "Smart TV 32inch", "Smart TV 43inch", "Soundbar", "Home Theater",
        "CCTV Camera", "WiFi Extender", "Mesh Router", "NAS Storage", "Server Rack", "Network Cable", "Fiber Cable", "Optical Drive",
        "DVD Writer", "Blu-ray Drive", "Thermal Paste", "Screwdriver Set", "Cable Organizer", "Laptop Sleeve", "Tablet Cover", "Phone Case",
        "Screen Protector", "Keyboard Cover", "Mouse Bungee", "Gaming Headset", "Noise Cancelling Headphones", "Studio Monitor", "Audio Interface", "MIDI Keyboard",
        "Drawing Tablet", "Stylus Pen", "Portable Monitor", "Mini PC", "Chromebook", "Ultrabook", "Gaming Laptop", "Workstation Laptop",
        "All-in-One PC", "Desktop PC", "Mini Tower", "Full Tower", "SFF PC", "Raspberry Pi", "Arduino Kit", "Soldering Iron",
        "Multimeter", "Oscilloscope", "Logic Analyzer", "3D Printer", "Filament PLA", "Filament ABS", "Resin Printer", "CNC Machine",
        "Laser Engraver", "Heat Gun", "Hot Air Station", "Magnifying Lamp", "Anti-static Mat", "ESD Wrist Strap", "Cable Tester", "Crimping Tool",
        "Network Tester", "Fiber Cleaver", "OTDR", "Spectrum Analyzer", "Signal Generator", "Power Meter", "LCR Meter", "Function Generator",
        "Digital Oscilloscope", "Logic Probe", "Breadboard", "Jumper Wires", "Resistor Kit", "Capacitor Kit"
    ],
    "Quantity": [
        2, 5, 3, 5, 8, 2, 18, 16, 15, 9, 7, 35, 6, 38, 28,
        3, 2, 6, 14, 15, 33, 39, 2, 36, 13, 35, 27, 15, 29, 38,
        18, 1, 11, 28, 22, 18, 10, 14, 22, 7, 6, 25, 7, 23, 23,
        39, 17, 3, 30, 35, 8, 25, 6, 36, 19, 40, 24, 37, 13, 5,
        3, 15, 19, 6, 15, 7, 25, 18, 30, 24, 11, 24, 23, 14, 18,
        5, 39, 11, 35, 16, 11, 30, 25, 18, 36, 15, 21, 4, 15, 3,
        21, 26, 18, 5, 14, 37, 21, 14, 32, 26, 30, 10, 17, 9, 16,
        36, 35, 17, 38, 28, 38, 26, 24, 15, 9, 33, 32, 6, 4, 8,
        10, 11, 28, 39, 5, 25, 25, 39, 30, 34, 17, 36, 1, 8, 35,
        18, 22, 8, 19, 28, 11, 30, 1, 17, 33, 12, 33, 7, 20, 33
    ],
    "Price": [
        50000, 500, 1500, 8500, 79918, 26171, 20132, 49109, 21274, 70797, 69614, 174, 78604, 42587, 64142,
        2652, 14762, 47676, 40406, 31485, 7692, 31671, 74464, 10422, 11326, 63799, 9171, 69922, 16583, 16928,
        62396, 72163, 21743, 34841, 69263, 79607, 55561, 27860, 70786, 26465, 40957, 52396, 49044, 57522, 67939,
        59277, 15960, 32593, 29551, 8492, 44413, 2857, 77210, 72703, 30261, 77228, 28964, 1042, 9405, 7816,
        30107, 8934, 4217, 43409, 9387, 67491, 31295, 36600, 63724, 28180, 70778, 17442, 74947, 75625, 62053,
        31950, 62093, 53454, 25057, 12463, 12804, 56598, 46538, 55619, 53983, 61313, 7200, 12999, 8044, 52872,
        44573, 14422, 32691, 25212, 25031, 70392, 58900, 18473, 55396, 24150, 36609, 60737, 32842, 9980, 58182,
        72232, 12933, 6730, 70955, 2034, 12324, 31082, 21898, 53369, 63753, 63192, 28116, 52665, 7785, 21679,
        49772, 382, 51273, 34860, 59738, 37488, 55544, 72945, 63888, 20389, 24990, 38990, 28634, 7765, 76014,
        71166, 8089, 41204, 7592, 6672, 76669, 62593, 66009, 69715, 20735, 7555, 66662, 10600, 24456, 9081
    ]
}

# Verification
print(len(data["Product"]), len(data["Quantity"]), len(data["Price"]))  # → 150 150 150

df = pd.DataFrame(data)
df

150 150 150

           Product  Quantity  Price
0           Laptop         2  50000
1            Mouse         5    500
2         Keyboard         3   1500
3              RAM         5   8500
4        SSD 512GB         8  79918
..             ...       ...    ...
145    Logic Probe        12   7555
146     Breadboard        33  66662
147   Jumper Wires         7  10600
148   Resistor Kit        20  24456
149  Capacitor Kit        33   9081

[150 rows x 3 columns]

In [7]:
df["Revenue"] = df["Quantity"] * df["Price"]
df

           Product  Quantity  Price  Revenue
0           Laptop         2  50000   100000
1            Mouse         5    500     2500
2         Keyboard         3   1500     4500
3              RAM         5   8500    42500
4        SSD 512GB         8  79918   639344
..             ...       ...    ...      ...
145    Logic Probe        12   7555    90660
146     Breadboard        33  66662  2199846
147   Jumper Wires         7  10600    74200
148   Resistor Kit        20  24456   489120
149  Capacitor Kit        33   9081   299673

[150 rows x 4 columns]

In [8]:
total_revenue = df["Revenue"].sum()
print("Total Revenue : ",total_revenue)

Total Revenue :  112819120

In [9]:
df.head()

     Product  Quantity  Price  Revenue
0     Laptop         2  50000   100000
1      Mouse         5    500     2500
2   Keyboard         3   1500     4500
3        RAM         5   8500    42500
4  SSD 512GB         8  79918   639344

In [10]:
df.tail()

           Product  Quantity  Price  Revenue
145    Logic Probe        12   7555    90660
146     Breadboard        33  66662  2199846
147   Jumper Wires         7  10600    74200
148   Resistor Kit        20  24456   489120
149  Capacitor Kit        33   9081   299673

In [11]:
df.sample(5)

              Product  Quantity  Price  Revenue
22          Mouse Pad         2  74464   148928
147      Jumper Wires         7  10600    74200
54          Webcam 4K        19  30261   574959
1               Mouse         5    500     2500
96   Screen Protector        21  58900  1236900

In [12]:
df.shape

(150, 4)

In [13]:
df.columns

Index(['Product', 'Quantity', 'Price', 'Revenue'], dtype='str')

In [14]:
df.dtypes

Product       str
Quantity    int64
Price       int64
Revenue     int64
dtype: object

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   150 non-null    str
 1   Quantity  150 non-null    int64
 2   Price     150 non-null    int64
 3   Revenue   150 non-null    int64
dtypes: int64(3), str(1)
memory usage: 4.8 KB

In [16]:
df.describe()

         Quantity         Price       Revenue
count  150.000000    150.000000  1.500000e+02
mean    19.280000  38368.526667  7.521275e+05
std     11.475167  24457.597664  7.326277e+05
min      1.000000    174.000000  2.500000e+03
25%      9.000000  15061.500000  1.631705e+05
50%     18.000000  34850.500000  4.934200e+05
75%     28.750000  61868.000000  1.112283e+06
max     40.000000  79918.000000  3.089120e+06

In [17]:
df.describe(include="all")

       Product    Quantity         Price       Revenue
count      150  150.000000    150.000000  1.500000e+02
unique     150         NaN           NaN           NaN
top     Laptop         NaN           NaN           NaN
freq         1         NaN           NaN           NaN
mean       NaN   19.280000  38368.526667  7.521275e+05
std        NaN   11.475167  24457.597664  7.326277e+05
min        NaN    1.000000    174.000000  2.500000e+03
25%        NaN    9.000000  15061.500000  1.631705e+05
50%        NaN   18.000000  34850.500000  4.934200e+05
75%        NaN   28.750000  61868.000000  1.112283e+06
max        NaN   40.000000  79918.000000  3.089120e+06

In [18]:
print(df.shape)

(150, 4)

In [19]:
print(df.isna().sum())

Product     0
Quantity    0
Price       0
Revenue     0
dtype: int64

In [20]:
print(df.nunique())

Product     150
Quantity     39
Price       150
Revenue     150
dtype: int64

In [21]:
print(df["Product"].value_counts())

Product
Laptop           1
Mouse            1
Keyboard         1
RAM              1
SSD 512GB        1
                ..
Logic Probe      1
Breadboard       1
Jumper Wires     1
Resistor Kit     1
Capacitor Kit    1
Name: count, Length: 150, dtype: int64

## Exercise 1 ##
Using the sales DataFrame from Lesson 1:
1. Display the first two records.
2. Find the number of rows and columns.
3. Display each column's data type.
4. Calculate the average product price.
5. Find the number of unique products.-

In [22]:
print(df.head(2))

  Product  Quantity  Price  Revenue
0  Laptop         2  50000   100000
1   Mouse         5    500     2500

In [23]:
print(df.shape)

(150, 4)

In [24]:
print(df.dtypes)

Product       str
Quantity    int64
Price       int64
Revenue     int64
dtype: object

In [25]:
print(df["Price"].mean())

38368.526666666665

In [26]:
print(df["Product"].nunique())

150

**Select, filter, and sort data**

In [27]:
# Select Columns 
df["Product"]

0             Laptop
1              Mouse
2           Keyboard
3                RAM
4          SSD 512GB
           ...
145      Logic Probe
146       Breadboard
147     Jumper Wires
148     Resistor Kit
149    Capacitor Kit
Name: Product, Length: 150, dtype: str

In [28]:
df[["Product", "Revenue"]].head()

     Product  Revenue
0     Laptop   100000
1      Mouse     2500
2   Keyboard     4500
3        RAM    42500
4  SSD 512GB   639344

**Select rows with loc and iloc**

In [29]:
df.loc[20, "Product"]

'Cabinet'

In [30]:
df.iloc[1:11]

           Product  Quantity  Price  Revenue
1            Mouse         5    500     2500
2         Keyboard         3   1500     4500
3              RAM         5   8500    42500
4        SSD 512GB         8  79918   639344
5          HDD 1TB         2  26171    52342
6   Monitor 24inch        18  20132   362376
7   Monitor 27inch        16  49109   785744
8        USB Cable        15  21274   319110
9       HDMI Cable         9  70797   637173
10          Webcam         7  69614   487298

**Filter rows using conditions**

In [31]:
expensive = df.loc[df["Price"] <= 500]

In [32]:
print(expensive)

          Product  Quantity  Price  Revenue
1           Mouse         5    500     2500
11     Headphones        35    174     6090
121  Oscilloscope        11    382     4202

In [33]:
df

           Product  Quantity  Price  Revenue
0           Laptop         2  50000   100000
1            Mouse         5    500     2500
2         Keyboard         3   1500     4500
3              RAM         5   8500    42500
4        SSD 512GB         8  79918   639344
..             ...       ...    ...      ...
145    Logic Probe        12   7555    90660
146     Breadboard        33  66662  2199846
147   Jumper Wires         7  10600    74200
148   Resistor Kit        20  24456   489120
149  Capacitor Kit        33   9081   299673

[150 rows x 4 columns]

In [34]:
result = df[
    (df["Price"] <= 800) & (df["Quantity"] >= 4) 
]

In [35]:
result

          Product  Quantity  Price  Revenue
1           Mouse         5    500     2500
11     Headphones        35    174     6090
121  Oscilloscope        11    382     4202

In [36]:
result = df[
    (df["Price"] >= 7000 & (df["Revenue"] < 10000))
]

In [37]:
result

           Product  Quantity  Price  Revenue
0           Laptop         2  50000   100000
1            Mouse         5    500     2500
2         Keyboard         3   1500     4500
3              RAM         5   8500    42500
4        SSD 512GB         8  79918   639344
..             ...       ...    ...      ...
145    Logic Probe        12   7555    90660
146     Breadboard        33  66662  2199846
147   Jumper Wires         7  10600    74200
148   Resistor Kit        20  24456   489120
149  Capacitor Kit        33   9081   299673

[150 rows x 4 columns]

In [38]:
df[df["Product"].isin(["Laptop", "Mouse","Webcam"])]

   Product  Quantity  Price  Revenue
0   Laptop         2  50000   100000
1    Mouse         5    500     2500
10  Webcam         7  69614   487298

In [39]:
df[df["Price"].between(500, 3000)]

               Product  Quantity  Price  Revenue
1                Mouse         5    500     2500
2             Keyboard         3   1500     4500
15         Motherboard         3   2652     7956
51   Graphics Card RTX        25   2857    71425
57           Projector        37   1042    38554
109          Ultrabook        28   2034    56952

In [40]:
df[df["Product"].str.contains("Board", case=False)]

                 Product  Quantity  Price  Revenue
2               Keyboard         3   1500     4500
15           Motherboard         3   2652     7956
34       Extension Board        22  69263  1523786
42   Mechanical Keyboard         7  49044   343308
43          RGB Keyboard        23  57522  1323006
45     Wireless Keyboard        39  59277  2311803
97        Keyboard Cover        14  18473   258622
103        MIDI Keyboard         9   9980    89820
146           Breadboard        33  66662  2199846

In [41]:
df[
    df["Product"].str.contains(
        "GB", case=True, na=False
    )
]

           Product  Quantity  Price  Revenue
4        SSD 512GB         8  79918   639344
24   Pendrive 32GB        13  11326   147238
25   Pendrive 64GB        35  63799  2232965
26  Pendrive 128GB        27   9171   247617
43    RGB Keyboard        23  57522  1323006
48         RAM 8GB        30  29551   886530
49        RAM 16GB        35   8492   297220
50        RAM 32GB         8  44413   355304
64    SD Card 64GB        15   9387   140805
65   SD Card 128GB         7  67491   472437
66   MicroSD 256GB        25  31295   782375

**Sort and rank**

In [42]:
df.sort_values("Revenue", ascending=False)

            Product  Quantity  Price  Revenue
55   Monitor 32inch        40  77228  3089120
127     CNC Machine        39  72945  2844855
108      Chromebook        38  70955  2696290
134    Cable Tester        35  76014  2660490
53        Webcam HD        36  72703  2617308
..              ...       ...    ...      ...
15      Motherboard         3   2652     7956
11       Headphones        35    174     6090
2          Keyboard         3   1500     4500
121    Oscilloscope        11    382     4202
1             Mouse         5    500     2500

[150 rows x 4 columns]

In [43]:
df.nlargest(15,"Revenue")

               Product  Quantity  Price  Revenue
55      Monitor 32inch        40  77228  3089120
127        CNC Machine        39  72945  2844855
108         Chromebook        38  70955  2696290
134       Cable Tester        35  76014  2660490
53           Webcam HD        36  72703  2617308
95          Phone Case        37  70392  2604504
105         Stylus Pen        36  72232  2600352
76     Smart TV 32inch        39  62093  2421627
45   Wireless Keyboard        39  59277  2311803
25       Pendrive 64GB        35  63799  2232965
146         Breadboard        33  66662  2199846
115         Full Tower        33  63192  2085336
84         Server Rack        36  53983  1943388
128     Laser Engraver        30  63888  1916640
68     Docking Station        30  63724  1911720

In [44]:
df["Revenue_Rank"] = df["Revenue"].rank(
    ascending=False,
    method="dense"
)

In [45]:
df

           Product  Quantity  Price  Revenue  Revenue_Rank
0           Laptop         2  50000   100000         126.0
1            Mouse         5    500     2500         150.0
2         Keyboard         3   1500     4500         148.0
3              RAM         5   8500    42500         140.0
4        SSD 512GB         8  79918   639344          63.0
..             ...       ...    ...      ...           ...
145    Logic Probe        12   7555    90660         128.0
146     Breadboard        33  66662  2199846          11.0
147   Jumper Wires         7  10600    74200         132.0
148   Resistor Kit        20  24456   489120          76.0
149  Capacitor Kit        33   9081   299673          97.0

[150 rows x 5 columns]

### Exercise 2: Sales filter ###
Create a DataFrame containing only products with:
- Price greater than ₹1,000.
- Revenue greater than ₹4,000.
- Revenue sorted from highest to lowest.

In [46]:
result = (
    df.loc[
        (df["Price"] > 1000) & (df["Revenue"] > 4000)
    ]
    . sort_values("Revenue", ascending=False)
)

In [47]:
result

             Product  Quantity  Price  Revenue  Revenue_Rank
55    Monitor 32inch        40  77228  3089120           1.0
127      CNC Machine        39  72945  2844855           2.0
108       Chromebook        38  70955  2696290           3.0
134     Cable Tester        35  76014  2660490           4.0
53         Webcam HD        36  72703  2617308           5.0
..               ...       ...    ...      ...           ...
118      Arduino Kit         4   7785    31140         143.0
16      Processor i5         2  14762    29524         144.0
132  Anti-static Mat         1  28634    28634         145.0
15       Motherboard         3   2652     7956         146.0
2           Keyboard         3   1500     4500         148.0

[147 rows x 5 columns]

## Create, transform, and modify columns ##

*Consider an employee dataset:*

In [48]:
employee = pd.DataFrame({
    "Name": [
        "Asha", "Rohan", "Priya", "Amit", "Neha", "Vikram", "Sneha", "Rahul",
        "Ananya", "Karan", "Meera", "Siddharth", "Pooja", "Arjun", "Divya", "Nikhil",
        "Riya", "Aditya", "Kavya", "Manish", "Shreya", "Harsh", "Isha", "Varun",
        "Tanvi", "Yash", "Nisha", "Rohan S", "Simran", "Aakash", "Priti", "Deepak",
        "Sonal", "Abhishek", "Kritika", "Gaurav", "Pallavi", "Ritesh", "Anjali", "Suresh",
        "Maya", "Kunal", "Swati", "Pranav", "Ritika", "Sagar", "Ayesha", "Vivek",
        "Nandini", "Mohit"
    ],
    "Department": [
        "IT", "HR", "R&D", "QA", "DevOps", "Dev", "Automation", "IT",
        "HR", "R&D", "QA", "DevOps", "Dev", "Automation", "IT", "HR",
        "R&D", "QA", "DevOps", "Dev", "Automation", "IT", "HR", "R&D",
        "QA", "DevOps", "Dev", "Automation", "IT", "HR", "R&D", "QA",
        "DevOps", "Dev", "Automation", "IT", "HR", "R&D", "QA", "DevOps",
        "Dev", "Automation", "IT", "HR", "R&D", "QA", "DevOps", "Dev",
        "Automation", "IT"
    ],
    "Salary": [
        60000, 50000, 40000, 50000, 72000, 68000, 55000, 75000,
        48000, 62000, 45000, 80000, 58000, 70000, 52000, 49000,
        65000, 47000, 78000, 71000, 54000, 69000, 51000, 64000,
        46000, 82000, 59000, 73000, 56000, 53000, 67000, 44000,
        76000, 61000, 57000, 74000, 50000, 63000, 48000, 79000,
        66000, 55000, 70000, 52000, 68000, 47000, 81000, 60000,
        54000, 72000
    ],
    "Experience": [
        0, 1, 2, 5, 3, 7, 4, 8,
        1, 6, 2, 10, 3, 9, 4, 1,
        5, 2, 11, 8, 3, 7, 1, 6,
        2, 12, 4, 9, 3, 2, 7, 1,
        10, 5, 4, 8, 2, 6, 1, 11,
        7, 3, 9, 2, 8, 1, 12, 5,
        4, 6
    ]
})

In [49]:
print(employee.shape)

(50, 4)

In [50]:
print(employee.dtypes)

Name            str
Department      str
Salary        int64
Experience    int64
dtype: object

In [51]:
print(employee.head())

    Name Department  Salary  Experience
0   Asha         IT   60000           0
1  Rohan         HR   50000           1
2  Priya        R&D   40000           2
3   Amit         QA   50000           5
4   Neha     DevOps   72000           3

In [52]:
print(employee.info())

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        50 non-null     str
 1   Department  50 non-null     str
 2   Salary      50 non-null     int64
 3   Experience  50 non-null     int64
dtypes: int64(2), str(2)
memory usage: 1.7 KB
None

In [53]:
print(employee.describe())

             Salary  Experience
count     50.000000   50.000000
mean   60920.000000    5.060000
std    11344.044558    3.346701
min    40000.000000    0.000000
25%    51250.000000    2.000000
50%    60000.000000    4.500000
75%    70000.000000    7.750000
max    82000.000000   12.000000

In [54]:
employee

         Name  Department  Salary  Experience
0        Asha          IT   60000           0
1       Rohan          HR   50000           1
2       Priya         R&D   40000           2
3        Amit          QA   50000           5
4        Neha      DevOps   72000           3
5      Vikram         Dev   68000           7
6       Sneha  Automation   55000           4
7       Rahul          IT   75000           8
8      Ananya          HR   48000           1
9       Karan         R&D   62000           6
10      Meera          QA   45000           2
11  Siddharth      DevOps   80000          10
12      Pooja         Dev   58000           3
13      Arjun  Automation   70000           9
14      Divya          IT   52000           4
15     Nikhil          HR   49000           1
16       Riya         R&D   65000           5
17     Aditya          QA   47000           2
18      Kavya      DevOps   78000          11
19     Manish         Dev   71000           8
20     Shreya  Automation   54000           3
21      Harsh          IT   69000           7
22       Isha          HR   51000           1
23      Varun         R&D   64000           6
24      Tanvi          QA   46000           2
25       Yash      DevOps   82000          12
26      Nisha         Dev   59000           4
27    Rohan S  Automation   73000           9
28     Simran          IT   56000           3
29     Aakash          HR   53000           2
30      Priti         R&D   67000           7
31     Deepak          QA   44000           1
32      Sonal      DevOps   76000          10
33   Abhishek         Dev   61000           5
34    Kritika  Automation   57000           4
35     Gaurav          IT   74000           8
36    Pallavi          HR   50000           2
37     Ritesh         R&D   63000           6
38     Anjali          QA   48000           1
39     Suresh      DevOps   79000          11
40       Maya         Dev   66000           7
41      Kunal  Automation   55000           3
42      Swati          IT   70000           9
43     Pranav          HR   52000           2
44     Ritika         R&D   68000           8
45      Sagar          QA   47000           1
46     Ayesha      DevOps   81000          12
47      Vivek         Dev   60000           5
48    Nandini  Automation   54000           4
49      Mohit          IT   72000           6

In [55]:
# Calculate annual salary if the existing salary is monthly 

employee["Annual_Salary"] = employee["Salary"] * 12

In [56]:
employee

         Name  Department  Salary  Experience  Annual_Salary
0        Asha          IT   60000           0         720000
1       Rohan          HR   50000           1         600000
2       Priya         R&D   40000           2         480000
3        Amit          QA   50000           5         600000
4        Neha      DevOps   72000           3         864000
5      Vikram         Dev   68000           7         816000
6       Sneha  Automation   55000           4         660000
7       Rahul          IT   75000           8         900000
8      Ananya          HR   48000           1         576000
9       Karan         R&D   62000           6         744000
10      Meera          QA   45000           2         540000
11  Siddharth      DevOps   80000          10         960000
12      Pooja         Dev   58000           3         696000
13      Arjun  Automation   70000           9         840000
14      Divya          IT   52000           4         624000
15     Nikhil          HR   49000           1         588000
16       Riya         R&D   65000           5         780000
17     Aditya          QA   47000           2         564000
18      Kavya      DevOps   78000          11         936000
19     Manish         Dev   71000           8         852000
20     Shreya  Automation   54000           3         648000
21      Harsh          IT   69000           7         828000
22       Isha          HR   51000           1         612000
23      Varun         R&D   64000           6         768000
24      Tanvi          QA   46000           2         552000
25       Yash      DevOps   82000          12         984000
26      Nisha         Dev   59000           4         708000
27    Rohan S  Automation   73000           9         876000
28     Simran          IT   56000           3         672000
29     Aakash          HR   53000           2         636000
30      Priti         R&D   67000           7         804000
31     Deepak          QA   44000           1         528000
32      Sonal      DevOps   76000          10         912000
33   Abhishek         Dev   61000           5         732000
34    Kritika  Automation   57000           4         684000
35     Gaurav          IT   74000           8         888000
36    Pallavi          HR   50000           2         600000
37     Ritesh         R&D   63000           6         756000
38     Anjali          QA   48000           1         576000
39     Suresh      DevOps   79000          11         948000
40       Maya         Dev   66000           7         792000
41      Kunal  Automation   55000           3         660000
42      Swati          IT   70000           9         840000
43     Pranav          HR   52000           2         624000
44     Ritika         R&D   68000           8         816000
45      Sagar          QA   47000           1         564000
46     Ayesha      DevOps   81000          12         972000
47      Vivek         Dev   60000           5         720000
48    Nandini  Automation   54000           4         648000
49      Mohit          IT   72000           6         864000

In [57]:
# create a businees classification 

employee["Experience_Level"] = np.where(
    employee["Experience"] >= 3,
    "Experience",
    "Junior"
)

In [58]:
employee

         Name  Department  Salary  Experience  Annual_Salary Experience_Level
0        Asha          IT   60000           0         720000           Junior
1       Rohan          HR   50000           1         600000           Junior
2       Priya         R&D   40000           2         480000           Junior
3        Amit          QA   50000           5         600000       Experience
4        Neha      DevOps   72000           3         864000       Experience
5      Vikram         Dev   68000           7         816000       Experience
6       Sneha  Automation   55000           4         660000       Experience
7       Rahul          IT   75000           8         900000       Experience
8      Ananya          HR   48000           1         576000           Junior
9       Karan         R&D   62000           6         744000       Experience
10      Meera          QA   45000           2         540000           Junior
11  Siddharth      DevOps   80000          10         960000       Experience
12      Pooja         Dev   58000           3         696000       Experience
13      Arjun  Automation   70000           9         840000       Experience
14      Divya          IT   52000           4         624000       Experience
15     Nikhil          HR   49000           1         588000           Junior
16       Riya         R&D   65000           5         780000       Experience
17     Aditya          QA   47000           2         564000           Junior
18      Kavya      DevOps   78000          11         936000       Experience
19     Manish         Dev   71000           8         852000       Experience
20     Shreya  Automation   54000           3         648000       Experience
21      Harsh          IT   69000           7         828000       Experience
22       Isha          HR   51000           1         612000           Junior
23      Varun         R&D   64000           6         768000       Experience
24      Tanvi          QA   46000           2         552000           Junior
25       Yash      DevOps   82000          12         984000       Experience
26      Nisha         Dev   59000           4         708000       Experience
27    Rohan S  Automation   73000           9         876000       Experience
28     Simran          IT   56000           3         672000       Experience
29     Aakash          HR   53000           2         636000           Junior
30      Priti         R&D   67000           7         804000       Experience
31     Deepak          QA   44000           1         528000           Junior
32      Sonal      DevOps   76000          10         912000       Experience
33   Abhishek         Dev   61000           5         732000       Experience
34    Kritika  Automation   57000           4         684000       Experience
35     Gaurav          IT   74000           8         888000       Experience
36    Pallavi          HR   50000           2         600000           Junior
37     Ritesh         R&D   63000           6         756000       Experience
38     Anjali          QA   48000           1         576000           Junior
39     Suresh      DevOps   79000          11         948000       Experience
40       Maya         Dev   66000           7         792000       Experience
41      Kunal  Automation   55000           3         660000       Experience
42      Swati          IT   70000           9         840000       Experience
43     Pranav          HR   52000           2         624000           Junior
44     Ritika         R&D   68000           8         816000       Experience
45      Sagar          QA   47000           1         564000           Junior
46     Ayesha      DevOps   81000          12         972000       Experience
47      Vivek         Dev   60000           5         720000       Experience
48    Nandini  Automation   54000           4         648000       Experience
49      Mohit          IT   72000           6         864000       Experience

In [59]:
employee["Experience_Level"]

0         Junior
1         Junior
2         Junior
3     Experience
4     Experience
5     Experience
6     Experience
7     Experience
8         Junior
9     Experience
10        Junior
11    Experience
12    Experience
13    Experience
14    Experience
15        Junior
16    Experience
17        Junior
18    Experience
19    Experience
20    Experience
21    Experience
22        Junior
23    Experience
24        Junior
25    Experience
26    Experience
27    Experience
28    Experience
29        Junior
30    Experience
31        Junior
32    Experience
33    Experience
34    Experience
35    Experience
36        Junior
37    Experience
38        Junior
39    Experience
40    Experience
41    Experience
42    Experience
43        Junior
44    Experience
45        Junior
46    Experience
47    Experience
48    Experience
49    Experience
Name: Experience_Level, dtype: str

In [60]:
# create multiple condition with np.select()

conditions = [
    employee["Salary"] >= 70000,
    employee["Salary"] >= 50000
]


labels = ["High", "Medium"]

employee["Salary_Band"] = np.select(
    conditions,
    labels,
    default="Low"
)

In [61]:
employee

,Name,Department,Salary,Experience,Annual_Salary,Experience_Level,Salary_Band
0,Asha,IT,60000,0,720000,Junior,Medium
1,Rohan,HR,50000,1,600000,Junior,Medium
2,Priya,R&D,40000,2,480000,Junior,Low
3,Amit,QA,50000,5,600000,Experience,Medium
4,Neha,DevOps,72000,3,864000,Experience,High
5,Vikram,Dev,68000,7,816000,Experience,Medium
6,Sneha,Automation,55000,4,660000,Experience,Medium
7,Rahul,IT,75000,8,900000,Experience,High
8,Ananya,HR,48000,1,576000,Junior,Low
9,Karan,R&D,62000,6,744000,Experience,Medium
10,Meera,QA,45000,2,540000,Junior,Low
11,Siddharth,DevOps,80000,10,960000,Experience,High
12,Pooja,Dev,58000,3,696000,Experience,Medium
13,Arjun,Automation,70000,9,840000,Experience,High
14,Divya,IT,52000,4,624000,Experience,Medium
15,Nikhil,HR,49000,1,588000,Junior,Low
16,Riya,R&D,65000,5,780000,Experience,Medium
17,Aditya,QA,47000,2,564000,Junior,Low
18,Kavya,DevOps,78000,11,936000,Experience,High
19,Manish,Dev,71000,8,852000,Experience,High
20,Shreya,Automation,54000,3,648000,Experience,Medium
21,Harsh,IT,69000,7,828000,Experience,Medium
22,Isha,HR,51000,1,612000,Junior,Medium
23,Varun,R&D,64000,6,768000,Experience,Medium
24,Tanvi,QA,46000,2,552000,Junior,Low
25,Yash,DevOps,82000,12,984000,Experience,High
26,Nisha,Dev,59000,4,708000,Experience,Medium
27,Rohan S,Automation,73000,9,876000,Experience,High
28,Simran,IT,56000,3,672000,Experience,Medium
29,Aakash,HR,53000,2,636000,Junior,Medium
30,Priti,R&D,67000,7,804000,Experience,Medium
31,Deepak,QA,44000,1,528000,Junior,Low
32,Sonal,DevOps,76000,10,912000,Experience,High
33,Abhishek,Dev,61000,5,732000,Experience,Medium
34,Kritika,Automation,57000,4,684000,Experience,Medium
35,Gaurav,IT,74000,8,888000,Experience,High
36,Pallavi,HR,50000,2,600000,Junior,Medium
37,Ritesh,R&D,63000,6,756000,Experience,Medium
38,Anjali,QA,48000,1,576000,Junior,Low
39,Suresh,DevOps,79000,11,948000,Experience,High
40,Maya,Dev,66000,7,792000,Experience,Medium
41,Kunal,Automation,55000,3,660000,Experience,Medium
42,Swati,IT,70000,9,840000,Experience,High
43,Pranav,HR,52000,2,624000,Junior,Medium
44,Ritika,R&D,68000,8,816000,Experience,Medium
45,Sagar,QA,47000,1,564000,Junior,Low
46,Ayesha,DevOps,81000,12,972000,Experience,High
47,Vivek,Dev,60000,5,720000,Experience,Medium
48,Nandini,Automation,54000,4,648000,Experience,Medium
49,Mohit,IT,72000,6,864000,Experience,High

In [62]:
employee["Salary_Band"]

0     Medium
1     Medium
2        Low
3     Medium
4       High
5     Medium
6     Medium
7       High
8        Low
9     Medium
10       Low
11      High
12    Medium
13      High
14    Medium
15       Low
16    Medium
17       Low
18      High
19      High
20    Medium
21    Medium
22    Medium
23    Medium
24       Low
25      High
26    Medium
27      High
28    Medium
29    Medium
30    Medium
31       Low
32      High
33    Medium
34    Medium
35      High
36    Medium
37    Medium
38       Low
39      High
40    Medium
41    Medium
42      High
43    Medium
44    Medium
45       Low
46      High
47    Medium
48    Medium
49      High
Name: Salary_Band, dtype: str

In [63]:
department_codes = {
    "IT" : "D01",
    "HR" : "D02" ,
    "Sales" : "D03", 
    "QA" : "D04",
    "Dev" :"D05",
    "Automation" : "D06",
    "DevOps" : "D07",
    "R&D" :"D08"
}

In [64]:
employee["Department_Code"] = employee["Department"].map(
    department_codes
)

In [65]:
employee

,Name,Department,Salary,Experience,Annual_Salary,Experience_Level,Salary_Band,Department_Code
0,Asha,IT,60000,0,720000,Junior,Medium,D01
1,Rohan,HR,50000,1,600000,Junior,Medium,D02
2,Priya,R&D,40000,2,480000,Junior,Low,D08
3,Amit,QA,50000,5,600000,Experience,Medium,D04
4,Neha,DevOps,72000,3,864000,Experience,High,D07
5,Vikram,Dev,68000,7,816000,Experience,Medium,D05
6,Sneha,Automation,55000,4,660000,Experience,Medium,D06
7,Rahul,IT,75000,8,900000,Experience,High,D01
8,Ananya,HR,48000,1,576000,Junior,Low,D02
9,Karan,R&D,62000,6,744000,Experience,Medium,D08
10,Meera,QA,45000,2,540000,Junior,Low,D04
11,Siddharth,DevOps,80000,10,960000,Experience,High,D07
12,Pooja,Dev,58000,3,696000,Experience,Medium,D05
13,Arjun,Automation,70000,9,840000,Experience,High,D06
14,Divya,IT,52000,4,624000,Experience,Medium,D01
15,Nikhil,HR,49000,1,588000,Junior,Low,D02
16,Riya,R&D,65000,5,780000,Experience,Medium,D08
17,Aditya,QA,47000,2,564000,Junior,Low,D04
18,Kavya,DevOps,78000,11,936000,Experience,High,D07
19,Manish,Dev,71000,8,852000,Experience,High,D05
20,Shreya,Automation,54000,3,648000,Experience,Medium,D06
21,Harsh,IT,69000,7,828000,Experience,Medium,D01
22,Isha,HR,51000,1,612000,Junior,Medium,D02
23,Varun,R&D,64000,6,768000,Experience,Medium,D08
24,Tanvi,QA,46000,2,552000,Junior,Low,D04
25,Yash,DevOps,82000,12,984000,Experience,High,D07
26,Nisha,Dev,59000,4,708000,Experience,Medium,D05
27,Rohan S,Automation,73000,9,876000,Experience,High,D06
28,Simran,IT,56000,3,672000,Experience,Medium,D01
29,Aakash,HR,53000,2,636000,Junior,Medium,D02
30,Priti,R&D,67000,7,804000,Experience,Medium,D08
31,Deepak,QA,44000,1,528000,Junior,Low,D04
32,Sonal,DevOps,76000,10,912000,Experience,High,D07
33,Abhishek,Dev,61000,5,732000,Experience,Medium,D05
34,Kritika,Automation,57000,4,684000,Experience,Medium,D06
35,Gaurav,IT,74000,8,888000,Experience,High,D01
36,Pallavi,HR,50000,2,600000,Junior,Medium,D02
37,Ritesh,R&D,63000,6,756000,Experience,Medium,D08
38,Anjali,QA,48000,1,576000,Junior,Low,D04
39,Suresh,DevOps,79000,11,948000,Experience,High,D07
40,Maya,Dev,66000,7,792000,Experience,Medium,D05
41,Kunal,Automation,55000,3,660000,Experience,Medium,D06
42,Swati,IT,70000,9,840000,Experience,High,D01
43,Pranav,HR,52000,2,624000,Junior,Medium,D02
44,Ritika,R&D,68000,8,816000,Experience,Medium,D08
45,Sagar,QA,47000,1,564000,Junior,Low,D04
46,Ayesha,DevOps,81000,12,972000,Experience,High,D07
47,Vivek,Dev,60000,5,720000,Experience,Medium,D05
48,Nandini,Automation,54000,4,648000,Experience,Medium,D06
49,Mohit,IT,72000,6,864000,Experience,High,D01

## Handle missing values correctly ##

In [67]:
employee.isna()

,Name,Department,Salary,Experience,Annual_Salary,Experience_Level,Salary_Band,Department_Code
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False

In [71]:
employee.isna().sum()

Name                0
Department          0
Salary              0
Experience          0
Annual_Salary       0
Experience_Level    0
Salary_Band         0
Department_Code     0
dtype: int64

In [72]:
employee.isna().mean() * 100

Name                0.0
Department          0.0
Salary              0.0
Experience          0.0
Annual_Salary       0.0
Experience_Level    0.0
Salary_Band         0.0
Department_Code     0.0
dtype: float64

In [73]:
employee.dropna()

,Name,Department,Salary,Experience,Annual_Salary,Experience_Level,Salary_Band,Department_Code
0,Asha,IT,60000,0,720000,Junior,Medium,D01
1,Rohan,HR,50000,1,600000,Junior,Medium,D02
2,Priya,R&D,40000,2,480000,Junior,Low,D08
3,Amit,QA,50000,5,600000,Experience,Medium,D04
4,Neha,DevOps,72000,3,864000,Experience,High,D07
5,Vikram,Dev,68000,7,816000,Experience,Medium,D05
6,Sneha,Automation,55000,4,660000,Experience,Medium,D06
7,Rahul,IT,75000,8,900000,Experience,High,D01
8,Ananya,HR,48000,1,576000,Junior,Low,D02
9,Karan,R&D,62000,6,744000,Experience,Medium,D08
10,Meera,QA,45000,2,540000,Junior,Low,D04
11,Siddharth,DevOps,80000,10,960000,Experience,High,D07
12,Pooja,Dev,58000,3,696000,Experience,Medium,D05
13,Arjun,Automation,70000,9,840000,Experience,High,D06
14,Divya,IT,52000,4,624000,Experience,Medium,D01
15,Nikhil,HR,49000,1,588000,Junior,Low,D02
16,Riya,R&D,65000,5,780000,Experience,Medium,D08
17,Aditya,QA,47000,2,564000,Junior,Low,D04
18,Kavya,DevOps,78000,11,936000,Experience,High,D07
19,Manish,Dev,71000,8,852000,Experience,High,D05
20,Shreya,Automation,54000,3,648000,Experience,Medium,D06
21,Harsh,IT,69000,7,828000,Experience,Medium,D01
22,Isha,HR,51000,1,612000,Junior,Medium,D02
23,Varun,R&D,64000,6,768000,Experience,Medium,D08
24,Tanvi,QA,46000,2,552000,Junior,Low,D04
25,Yash,DevOps,82000,12,984000,Experience,High,D07
26,Nisha,Dev,59000,4,708000,Experience,Medium,D05
27,Rohan S,Automation,73000,9,876000,Experience,High,D06
28,Simran,IT,56000,3,672000,Experience,Medium,D01
29,Aakash,HR,53000,2,636000,Junior,Medium,D02
30,Priti,R&D,67000,7,804000,Experience,Medium,D08
31,Deepak,QA,44000,1,528000,Junior,Low,D04
32,Sonal,DevOps,76000,10,912000,Experience,High,D07
33,Abhishek,Dev,61000,5,732000,Experience,Medium,D05
34,Kritika,Automation,57000,4,684000,Experience,Medium,D06
35,Gaurav,IT,74000,8,888000,Experience,High,D01
36,Pallavi,HR,50000,2,600000,Junior,Medium,D02
37,Ritesh,R&D,63000,6,756000,Experience,Medium,D08
38,Anjali,QA,48000,1,576000,Junior,Low,D04
39,Suresh,DevOps,79000,11,948000,Experience,High,D07
40,Maya,Dev,66000,7,792000,Experience,Medium,D05
41,Kunal,Automation,55000,3,660000,Experience,Medium,D06
42,Swati,IT,70000,9,840000,Experience,High,D01
43,Pranav,HR,52000,2,624000,Junior,Medium,D02
44,Ritika,R&D,68000,8,816000,Experience,Medium,D08
45,Sagar,QA,47000,1,564000,Junior,Low,D04
46,Ayesha,DevOps,81000,12,972000,Experience,High,D07
47,Vivek,Dev,60000,5,720000,Experience,Medium,D05
48,Nandini,Automation,54000,4,648000,Experience,Medium,D06
49,Mohit,IT,72000,6,864000,Experience,High,D01

In [74]:
customers  = pd.DataFrame({
    "Customer" : ["Asha", "Rohan", "Priya", "Amit", "Neha"],
    "Age" : [25, np.nan, 32,28,np.nan],
    "City" : ["Pune", "Mumbai", np.nan, "Pune", "Delhi"],
    "Income" : [40000, 50000, np.nan, 45000, 60000]
})

In [75]:
customers

  Customer   Age    City   Income
0     Asha  25.0    Pune  40000.0
1    Rohan   NaN  Mumbai  50000.0
2    Priya  32.0     NaN      NaN
3     Amit  28.0    Pune  45000.0
4     Neha   NaN   Delhi  60000.0

In [76]:
customers["Age"] = customers["Age"].fillna(
    customers["Age"].median()
)

customers["City"] = customers["City"].fillna("Unknown")

In [77]:
customers

  Customer   Age     City   Income
0     Asha  25.0     Pune  40000.0
1    Rohan  28.0   Mumbai  50000.0
2    Priya  32.0  Unknown      NaN
3     Amit  28.0     Pune  45000.0
4     Neha  28.0    Delhi  60000.0

In [78]:
know_income_total = customers["Income"].sum()

In [81]:
print(know_income_total)

195000.0

## Exercise 3 ##
1. Find missing values in each column.
2. Calculate the percentage missing.
3. Fill missing ages with the median.
4. Fill missing cities with "Unknown".
5. Explain why filling a missing customer ID with the mean would be invalid.

In [82]:
missing_count =  customers.isnull().sum()

In [83]:
missing_count

Customer    0
Age         0
City        0
Income      1
dtype: int64

In [84]:
missing_pct = customers.isnull().mean() * 100

In [85]:
missing_pct

Customer     0.0
Age          0.0
City         0.0
Income      20.0
dtype: float64

In [86]:
# Fill missing Age with median and City with "Unknown"
customers["Age"] = customers["Age"].fillna(customers["Age"].median())
customers["City"] = customers["City"].fillna("Unknown")

In [87]:
customers

  Customer   Age     City   Income
0     Asha  25.0     Pune  40000.0
1    Rohan  28.0   Mumbai  50000.0
2    Priya  32.0  Unknown      NaN
3     Amit  28.0     Pune  45000.0
4     Neha  28.0    Delhi  60000.0

## Duplicates, data types, and data validation ##

In [90]:
customers.duplicated().sum()

np.int64(0)

In [91]:
customers.drop_duplicates()

  Customer   Age     City   Income
0     Asha  25.0     Pune  40000.0
1    Rohan  28.0   Mumbai  50000.0
2    Priya  32.0  Unknown      NaN
3     Amit  28.0     Pune  45000.0
4     Neha  28.0    Delhi  60000.0

In [98]:
orders = pd.DataFrame({
    "Order_ID": [101, 102, 102, 103],
    "Customer": ["A", "B", "B", "C"],
    "Amount": [500, 800, 800, 900]
})

orders.drop_duplicates(subset=["Order_ID"])

   Order_ID Customer  Amount
0       101        A     500
1       102        B     800
3       103        C     900

In [95]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [96]:
df

           Product  Quantity  Price  Revenue  Revenue_Rank
0           Laptop         2  50000   100000         126.0
1            Mouse         5    500     2500         150.0
2         Keyboard         3   1500     4500         148.0
3              RAM         5   8500    42500         140.0
4        SSD 512GB         8  79918   639344          63.0
..             ...       ...    ...      ...           ...
145    Logic Probe        12   7555    90660         128.0
146     Breadboard        33  66662  2199846          11.0
147   Jumper Wires         7  10600    74200         132.0
148   Resistor Kit        20  24456   489120          76.0
149  Capacitor Kit        33   9081   299673          97.0

[150 rows x 5 columns]

In [100]:
orders["Order_Date"] = pd.to_datetime(
    orders["Order_Date"],
    errors="coerce"
)

KeyError: 'Order_Date'

In [101]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [102]:
df

           product  quantity  price  revenue  revenue_rank
0           Laptop         2  50000   100000         126.0
1            Mouse         5    500     2500         150.0
2         Keyboard         3   1500     4500         148.0
3              RAM         5   8500    42500         140.0
4        SSD 512GB         8  79918   639344          63.0
..             ...       ...    ...      ...           ...
145    Logic Probe        12   7555    90660         128.0
146     Breadboard        33  66662  2199846          11.0
147   Jumper Wires         7  10600    74200         132.0
148   Resistor Kit        20  24456   489120          76.0
149  Capacitor Kit        33   9081   299673          97.0

[150 rows x 5 columns]

In [103]:
customers["City"] = (
    customers["City"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [104]:
customers

  Customer   Age     City   Income
0     Asha  25.0     Pune  40000.0
1    Rohan  28.0   Mumbai  50000.0
2    Priya  32.0  Unknown      NaN
3     Amit  28.0     Pune  45000.0
4     Neha  28.0    Delhi  60000.0